<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="estilo.css"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 23/01/2020
 Documento.- 10.xml
--> 
<!DOCTYPE clase [
	<!ELEMENT estudiante (nombre)>
	<!ELEMENT nombre (#PCDATA)>
	<!ATTLIST estudiante codigo ID #REQUIRED>
	<!ATTLIST estudiante tutor IDREFS #IMPLIED>
	<!ELEMENT clase (estudiante*)>
]>

<clase>
	<estudiante codigo="A01">
		<nombre>Susana</nombre>
	</estudiante>
	<estudiante codigo="A02" tutor="A01">
		<nombre>Javier</nombre>
	</estudiante>
</clase>