=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/schemas/02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 11/02/2020
 Documento.- 02.xsd
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mundo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="continente" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nCont" type="xs:string"/>
							<xs:element name="pais" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nPais" type="xs:string"/>
										<xs:element name="capital">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nCap" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 20/01/2020
 Documento.- 02.xml
-->
<!DOCTYPE mundo [
	<!ELEMENT continente (nCont, pais+)>
	<!ELEMENT nCont (#PCDATA)>
	<!ELEMENT pais (nPais, capital)>
	<!ELEMENT nPais (#PCDATA)>
	<!ELEMENT capital (nCap)>
	<!ELEMENT nCap (#PCDATA)>
	<!ELEMENT mundo (continente+)>
	
	<!ATTLIST mail xmlns:xsi CDATA #IMPLIED>
	<!ATTLIST mail xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]>

<mundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/02.xsd">
	<continente>
		<nCont>Europa</nCont>
		<pais>
			<nPais>Alemania</nPais>
			<capital>
				<nCap>Berlín</nCap>
			</capital>
		</pais>
	</continente>
	<continente>
		<nCont>América</nCont>
		<pais>
			<nPais>Argentina</nPais>
			<capital>
				<nCap>Buenos Aires</nCap>
			</capital>
		</pais>
		<pais>
			<nPais>Bahamas</nPais>
			<capital>
				<nCap>Nassau</nCap>
			</capital>
		</pais>
	</continente>
	<continente>
		<nCont>Asia</nCont>
		<pais>
			<nPais>Afganistán</nPais>
			<capital>
				<nCap>Kabul</nCap>
			</capital>
		</pais>
		<pais>
			<nPais>Arabia Saudita</nPais>
			<capital>
				<nCap>Riad</nCap>
			</capital>
		</pais>
	</continente>
</mundo>
