=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/schemas/03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="hechos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="descripcion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="texto" type="xs:string"/>
							<xs:element name="fecha">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dia" type="xs:gDay"/>
										<xs:element name="mes" type="xs:gMonth"/>
										<xs:element name="aÃ±o" type="xs:gYear"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/03.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 20/01/2020
 Documento.- 03.xml
-->
<!DOCTYPE hechos [
	<!ELEMENT descripcion (texto, fecha)>
	<!ELEMENT texto (#PCDATA)>
	<!ELEMENT fecha (dia, mes, año)>
	<!ELEMENT dia (#PCDATA)>
	<!ELEMENT mes (#PCDATA)>
	<!ELEMENT año (#PCDATA)>
	<!ELEMENT hechos (descripcion+)>
]>

<hechos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/03.xsd">
	<descripcion>
		<texto>Se funda Youtube</texto>
		<fecha>
			<dia>15</dia>
			<mes>2</mes>
			<año>2005</año>
		</fecha>
	</descripcion>
	<descripcion>
		<texto>Se funda Google</texto>
		<fecha>
			<dia>4</dia>
			<mes>9</mes>
			<año>1998</año>
		</fecha>
	</descripcion>
	<descripcion>
		<texto>Se funda Facebook</texto>
		<fecha>
			<dia>4</dia>
			<mes>2</mes>
			<año>2004</año>
		</fecha>
	</descripcion>
</hechos>
