=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/schemas/04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mail">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="remitente" type="xs:string"/>
				<xs:element name="destinatario">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="correo" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="asunto" type="xs:string" minOccurs="0"/>
				<xs:element name="mensaje" type="xs:string"/>
				<xs:element name="adjuntos" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="image" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="tipo">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:pattern value="png|jpg"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="fecha" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/04.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 11/02/2020
 Documento.- 04.xml
-->
<!DOCTYPE mail [
	<!ELEMENT mail (fecha, remitente, destinatario, asunto?, mensaje, adjuntos)>
	
	<!ELEMENT remitente (#PCDATA)>
	<!ELEMENT destinatario (correo+)>
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT mensaje (#PCDATA)>
	<!ELEMENT adjuntos (image*)>
	
	<!ELEMENT correo (#PCDATA)>
	<!ELEMENT image (tipo, nombre)>
	
	<!ELEMENT nombre (#PCDATA)>
	
	<!ATTLIST mail xmlns:xsi CDATA #IMPLIED>
	<!ATTLIST mail xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
	<!ATTLIST mail fecha CDATA #REQUIRED>
	
	<!ATTLIST image tipo (png|jpg) #REQUIRED>
]>
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/04.xsd" fecha="2020-01-14">
	<remitente>marodriguezn@educa.jcyl.es</remitente>
	<destinatario>
		<correo>eduardo@educa.jcyl.es</correo>
		<correo>maria@educa.jcyl.es</correo>
	</destinatario>
	<asunto>Fiesta de fin de curso</asunto>
	<mensaje> A las 20:00 en ...</mensaje>
	<adjuntos>
		<image tipo="png">foto1.png</image>
		<image tipo="png">foto2.png</image>
	</adjuntos>
</mail>
