=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/schemas/05.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 11/02/2020
 Documento.- 05.xsd
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mundo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="continente" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nCont" type="xs:string"/>
							<xs:element name="pais" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="capital" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/05.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 20/01/2020
 Documento.- 05.xml
-->
 

<mundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/05.xsd">
	<continente>
		<nCont>Europa</nCont>
		<pais capital="Berlin">Alemania</pais>
	</continente>
	<continente>
		<nCont>América</nCont>
		<pais capital="Buenos Aires">Argentina</pais>
		<pais capital="Nassau">Bahamas</pais>
	</continente>
	<continente>
		<nCont>Asia</nCont>
		<pais capital="Kabul">Afganistán</pais>
		<pais capital="Riad">Arabia Saudita</pais>
	</continente>
	<continente>
		<nCont>África</nCont>
	</continente>
</mundo>
