=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/schemas/15.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 13/02/2020
 Documento.- 15.xsd
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Tipos Simples -->
	<xs:simpleType name="tipoLuminosidad">
		<xs:restriction base="xs:integer"/>
	</xs:simpleType>
	
	<xs:simpleType name="tipoHemisferio">
		<!-- tipoHemisferio es un tipo simple que toma los valores "Norte" o "Sur" -->
		<xs:restriction base="xs:string">
			<xs:enumeration value="Norte"/>
			<xs:enumeration value="Sur"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipoMesEnLetra">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Enero"/>
			<xs:enumeration value="Febrero"/>
			<xs:enumeration value="Marzo"/>
			<xs:enumeration value="Abril"/>
			<xs:enumeration value="Mayo"/>
			<xs:enumeration value="Junio"/>
			<xs:enumeration value="Julio"/>
			<xs:enumeration value="Agosto"/>
			<xs:enumeration value="Septiembre"/>
			<xs:enumeration value="Octubre"/>
			<xs:enumeration value="Noviembre"/>
			<xs:enumeration value="Diciembre"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Elementos -->
	<xs:element name="mapaEstelar">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="constelacion">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"/>
							<xs:element name="superficie" type="xs:float"/>
							<xs:element name="estrellas">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="asterismo" type="xs:integer"/>
										<xs:element name="masBrillante">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="luminosidad" type="tipoLuminosidad"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="numEstrellas" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="objetos">
								<xs:complexType>
									<xs:sequence>
										<!-- Elementos vacios complejos, con atributos de tipo booleano -->
										<xs:element name="cumulos">
											<xs:complexType>
												<xs:attribute name="tiene" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="nebulosas">
											<xs:complexType>
												<xs:attribute name="tiene" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="galaxias">
											<xs:complexType>
												<xs:attribute name="tiene" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="cuasares">
											<xs:complexType>
												<xs:attribute name="tiene" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="lluviasMeteoros">
											<xs:complexType>
												<xs:attribute name="tiene" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="observacion">
								<xs:complexType>
									<xs:sequence>
										<!-- El elemento hemisferio solo puede tomar los valores "Norte" o "Sur" -->
										<xs:element name="hemisferio" type="tipoHemisferio"/>
										<!-- cambiar a tipo gMonth -->
										<xs:element name="mes" type="xs:string"/>
										<!-- cambiar a tipo hora -->
										<xs:element name="hora" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="otrosDatos">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="informacion" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<!-- El atributo "nomLatin" es obligatorio -->
						<xs:attribute name="nomLatin" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SusanaFASauces/Proyecto1920_LMSGI_SFA/Fuentes/practicas/ud4/15.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 Autor.- Susana Fabián Antón
 Fecha.- 13/02/2020
 Documento.- 15.xml
-->
<mapaEstelar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/15.xsd">
	<!-- El atributo "nomLatin" es obligatorio -->
	<constelacion nomLatin="Ursa Maior">
		<nombre>Osa Mayor</nombre>
		<superficie>1279.7</superficie>
		<estrellas numEstrellas="209">
			<asterismo>7</asterismo>
			<masBrillante luminosidad="108">Alioth</masBrillante>
		</estrellas>
		<objetos>
			<!-- Elementos vacios con atributos de tipo booleano -->
			<cumulos tiene="false"/>
			<nebulosas tiene="true"/>
			<galaxias tiene="true"/>
			<cuasares tiene="false"/>
			<lluviasMeteoros tiene="true"/>
		</objetos>
		<observacion>
			<!-- El elemento hemisferio solo puede tomar los valores "Norte" o "Sur" -->
			<hemisferio>Norte</hemisferio>
			<!-- cambiar tipo a gMonth -->
			<mes>Abril</mes>
			<!-- cambiar tipo a time -->
			<hora>21:00</hora>
		</observacion>
		<otrosDatos>
			<informacion>
				En esta constelación podemos observar Mizar y Alcor,
				que forman una estrella doble óptica, de las más 
				reconocidas del cielo nocturno
			</informacion>
		</otrosDatos>
	</constelacion>
</mapaEstelar>
